---
title: "NYC Restaurant Inspections Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)
library(flexdashboard)
library(plotly)
```

```{r, include=FALSE}
data("rest_inspec")

rest_inspec = 
  rest_inspec %>% 
  mutate(
    inspection_date = as.Date(inspection_date)
  ) %>% 
  separate(inspection_date, into = c("year", "month", "day"), sep = "-") %>%
  select(camis, dba, boro, zipcode, cuisine_description, year, critical_flag, score, grade) %>% 
  filter(
    boro != "Missing"
  ) %>% 
  sample_n(10000) 
```

This dashboard contains interactive graphics for NYC restaurant inspection data. More details about the grading and scoring process can be found [here](https://www1.nyc.gov/assets/doh/downloads/pdf/rii/how-we-score-grade.pdf).

Column {data-width=650}
-----------------------------------------------------------------------

### Inspection scores for restaurants in the five boroughs of NYC

```{r}
rest_inspec %>% 
  plot_ly(
    y = ~score, color = ~boro,
    type = "box", colors = "viridis"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Number of critical violations across restuarants in each borough

```{r}
rest_inspec %>% 
  filter(
    critical_flag == "Critical"
  ) %>% 
  count(boro) %>% 
  plot_ly(
    x = ~boro, y = ~n,
    type = "bar"
  ) %>% 
  layout(xaxis = list(title = "borough"), 
         yaxis = list(title = "# of critical violations"))
```

### Frequency distribution of inspection scores across all restuarnts in NYC

```{r}
rest_inspec %>% 
  plot_ly(
    x = ~score, type = "histogram", color = "orange"
  ) %>%
  layout(xaxis = list(title = "Score"), 
         yaxis = list(title = "Frequency"))
```

